[build]
  publish = "."

[[redirects]]
  from = "/session"
  to = "https://icallon-262474602690.africa-south1.run.appp/session"
  status = 200
  force = true

[[redirects]]
  from = "/socket.io/*"
  to = "https://icallon-262474602690.africa-south1.run.app/socket.io/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200